[tools]
go = "latest"
java = "21"
maven = "latest"
lua = "latest"
node = "20"
python = "latest"
ruby = "latest"
rust = "latest"
yarn = "latest"
pipx = "latest"

[settings]
idiomatic_version_file_enable_tools = []
